[frontend]
172.31.45.33

[catalogue]
172.31.39.14

[user]
172.31.39.15

[cart]
172.31.39.16

; group of groups 
[roboshop:children]
frontend
catalogue
user
cart

[local]
localhost

; local group vars 
[local:vars]
COURSE="Ansible"
TRAINER="Sivakumar"
Duration="10HRS"
